# -*- coding: utf-8 -*-
"""pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e3xfO66wNejYS-cJbar31-I6Zn3AtQjE
"""

import pandas as pd
import json
import datetime

# ---------------------------------------------------------
# 1. SIMULATE THE DATA
# ---------------------------------------------------------
# Simulated Pharmacy Claims (Messy data from providers)
claims_data = [
    {"claim_id": "CLM-001", "member_id": "M100", "ndc": "00069-3150-83", "billed_amount": 450.00}, # Lipitor (Brand)
    {"claim_id": "CLM-002", "member_id": "M101", "ndc": "00093-7152-98", "billed_amount": 15.00},  # Atorvastatin (Generic)
    {"claim_id": "CLM-003", "member_id": "M102", "ndc": "00004-0038-22", "billed_amount": 380.00}, # Lexapro (Brand)
]

# Simulated Drug Reference/Formulary Table
formulary_data = [
    {"ndc": "00069-3150-83", "drug_name": "Lipitor", "type": "Brand", "generic_available": True, "expected_generic_cost": 12.00},
    {"ndc": "00093-7152-98", "drug_name": "Atorvastatin", "type": "Generic", "generic_available": False, "expected_generic_cost": 12.00},
    {"ndc": "00004-0038-22", "drug_name": "Lexapro", "type": "Brand", "generic_available": True, "expected_generic_cost": 10.00},
]

df_claims = pd.DataFrame(claims_data)
df_formulary = pd.DataFrame(formulary_data)

# ---------------------------------------------------------
# 2. THE PIPELINE LOGIC (Unpacking the 3%)
# ---------------------------------------------------------
def process_claims(claims, formulary):
    # Join claims with formulary data
    df_merged = pd.merge(claims, formulary, on="ndc", how="left")

    flagged_claims = []
    claim_traces = {}

    for _, row in df_merged.iterrows():
        claim_id = row['claim_id']
        trace = {
            "claim_id": claim_id,
            "timestamp": datetime.datetime.now().isoformat(),
            "execution_plan": []
        }

        # Module 1: Ingestion
        trace["execution_plan"].append({"module": "Ingestion", "status": "Success", "data": {"ndc": row['ndc'], "billed": row['billed_amount']}})

        # Module 2: Formulary Check
        if pd.isna(row['type']):
            trace["execution_plan"].append({"module": "Formulary_Check", "status": "Failed", "reason": "NDC not found in formulary"})
            claim_traces[claim_id] = trace
            continue

        trace["execution_plan"].append({"module": "Formulary_Check", "status": "Success", "drug_type": row['type']})

        # Module 3: Affordability & Generic Substitution Check
        if row['type'] == 'Brand' and row['generic_available']:
            cost_difference = row['billed_amount'] - row['expected_generic_cost']
            if cost_difference > 50.00: # Arbitrary threshold for "expensive" missed savings
                trace["execution_plan"].append({
                    "module": "Affordability_Check",
                    "status": "Flagged",
                    "reason": "Costly Brand dispensed when Generic available",
                    "missed_savings": round(cost_difference, 2)
                })
                flagged_claims.append(row.to_dict())
            else:
                trace["execution_plan"].append({"module": "Affordability_Check", "status": "Passed"})
        else:
             trace["execution_plan"].append({"module": "Affordability_Check", "status": "Passed", "reason": "Generic dispensed or no generic available"})

        claim_traces[claim_id] = trace

    return flagged_claims, claim_traces

# ---------------------------------------------------------
# 3. EXECUTE & OUTPUT
# ---------------------------------------------------------
flagged, traces = process_claims(df_claims, df_formulary)

print(f"--- Processed {len(df_claims)} claims. Flagged {len(flagged)} for affordability review. ---\n")

# Print the Oscar-style Claim Trace for a flagged claim
print("SAMPLE CLAIM TRACE (JSON LOG):")
print(json.dumps(traces["CLM-001"], indent=4))